---
- name: This Playbook install for httpd 
  hosts: appserver
  become: true
  tasks:
  - name: Installing  httpd
    yum:
      name: httpd
      state: installed

  - name: Start the httpd
    service:
      name: httpd      
      state: started
  
